### ISSUE TITLE
How to debug "[error] java.util.NoSuchElementException: None.get"?

### ISSUE THREAD

**Issue by julien-truffaut** [olafurpg/sbt-ci-release#146]
Hi all,

I am getting the folllowing error when I run `sbt ci-release`

```
[info] resolving key references (17143 settings) ...
[error] java.util.NoSuchElementException: None.get
[error] Use 'last' for the full log.
```

Here is the [run](https://github.com/optics-dev/Monocle/runs/1202365227)

is there a way to figure out what is missing?

**Comment by julien-truffaut** [comment]
Locally, I can run `sbt ci-release`, the issue is only on CI.

**Comment by keynmol** [comment]
@julien-truffaut 

Could it be https://github.com/optics-dev/Monocle/blob/master/build.sbt#L310 ?

I'm gonna go on a tangent here and assume that previousStableVersion fails because sbt-dynver tries to pick up latest version from tags, but by default github checkout action actually doesn't fetch tags.

In my setup with sbt-ci-release I actually run one more action before sbt ci-release:

```
      - run: git fetch --unshallow
```

And the reason you can't reproduce locally is because you don't have a shallow copy, so everything goes swimmingly

**Comment by keynmol** [comment]
Supporting my theory is the actual `--no-tags` flag used by checkout action:

https://github.com/optics-dev/Monocle/runs/1202365227#step:2:30

**Comment by julien-truffaut** [comment]
Thanks a lot @keynmol I would never found this out. Indeed, `git fetch --unshallow` fixed the problem.
