### ISSUE TITLE
wrong location? /home/travis/.sbt/gpg/secring.asc

### ISSUE THREAD

**Issue by ThijsBroersen** [olafurpg/sbt-ci-release#26]
When I set CI_RELEASE to publishSigned (instead of +publishSigned to only build a single Scala version at the time) it somehow got a wrong reference to the keyring. PGP_SECRET is import the same way as with +publishSigned. But after compiling the sources it looks at /home/travis/.sbt/gpg/secring.asc for the secret and cannot find it. 

How can this happen?

**Comment by olafurpg** [comment]
Thanks for reporting! I have not seen this error before. Does your build or an installed sbt plugin define custom settings from sbt-pgp?

**Comment by ThijsBroersen** [comment]
No, it just happens when I add CI_RELEASE=publishSigned to Travis env.vars. Without the env.var it stages everything correctly but cannot publish because 'multiple repositories are found' (due to cross-building).

**Comment by olafurpg** [comment]
The `CI_RELEASE` environment variable is picked up here https://github.com/olafurpg/sbt-ci-release/blob/e639aabe393e0c748014937c9cc678bfe559cdcf/plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala#L66 

A good way to debug this is to publish the project first from your local machine with `publishSigned` and `sonatypeRelease`.

**Comment by ThijsBroersen** [comment]
Did a lot of testing but on my local machine the gpg version is different. Tried the latest version of sbt-pgp but this also led to issues. For now I just cross-build at once and use 'sonatypeReleaseAll' (but this prevents my from publishing other projects/tags simultaneously).
Created an issue @sbt-sonatype https://github.com/xerial/sbt-sonatype/issues/78

**Comment by olafurpg** [comment]
> but this prevents my from publishing other projects/tags simultaneously

We experience the same problem when publishing for organizations like `org.scalameta` and `ch.epfl.scala`, it would be nice indeed to improve this.

I'm gonna close this issue here since it's not clear how it can be fixed in sbt-ci-release. This plugin is a wrapper around its dependencies and is only 90 loc https://github.com/olafurpg/sbt-ci-release/blob/e639aabe393e0c748014937c9cc678bfe559cdcf/plugin/src/main/scala/com/geirsson/CiReleasePlugin.scala#L66
